name: NPM Deprecate PR versions On Merge

on:
    pull_request:
        types:
            - closed

jobs:
    deprecate-on-merge:
        name: NPM Deprecate PR versions On Merge
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
            - name: Use Node.js v18
              uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
              with:
                  node-version: 18
                  cache: yarn
                  registry-url: https://registry.npmjs.org/
            - name: Install Dependencies
              run: yarn --immutable
            - name: Deprecate versions
              run: true || yarn npm-deprecate --name "*pr-${PR_NUMBER}*" -d -v
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
                  PR_NUMBER: ${{ github.event.number }}
